# Version

* `v7`: yolo26x_fold4_finetune768 tta768 conf_thr=0.01
* `v6`: yolo26x_fold3_finetune768 tta768 conf_thr=0.01
* `v5`: yolo26x_fold2_finetune768 tta768 conf_thr=0.01
* `v4`: yolo26x_fold1_finetune768 tta768 conf_thr=0.01
* `v3`: yolo26x_fold0_finetune768 tta768 conf_thr=0.01

# [Training Notebook](https://www.kaggle.com/awsaf49/vinbigdata-cxr-ad-yolov5-14-class)
* Select `GPU` as the **Accelerator**

In [1]:
import numpy as np, pandas as pd
from glob import glob
import shutil, os
import matplotlib.pyplot as plt
from sklearn.model_selection import GroupKFold
from tqdm.notebook import tqdm
import seaborn as sns

In [2]:
dim = 1024 #1024, 256, 'original'
test_dir = f'/kaggle/input/vinbigdata-{dim}-image-dataset/vinbigdata/test'
# YOLO26x Fold 0 finetune768
weights_dir = '/kaggle/input/datasets/wokhyu/vinbigdata-final-models-yolo26x/yolo26x_fold4_finetune768_best.pt'

In [3]:
test_df = pd.read_csv(f'/kaggle/input/vinbigdata-{dim}-image-dataset/vinbigdata/test.csv')
test_df.head()

                           image_id  width  height
0  83caa8a85e03606cf57e49147d7ac569   2304    2880
1  7550347fa2bb96c2354a3716dfa3a69c   2538    3095
2  74b23792db329cff5843e36efb8aa65a   2788    3120
3  94568a546be103177cb582d3e91cd2d8   1994    2430
4  6da36354fc904b63bc03eb3884e0c35c   2056    2376

# YOLO26 Setup

In [4]:
!pip install ultralytics -q

import torch
from IPython.display import Image, clear_output

clear_output()
print('Setup complete. Using torch %s %s' % (torch.__version__, torch.cuda.get_device_properties(0) if torch.cuda.is_available() else 'CPU'))

Setup complete. Using torch 2.10.0+cu128 _CudaDeviceProperties(name='Tesla T4', major=7, minor=5, total_memory=14912MB, multi_processor_count=40, uuid=755d2b20-fd49-8921-36bb-932207412043, pci_bus_id=0, pci_device_id=4, pci_domain_id=0, L2_cache_size=4MB)

In [5]:
# ultralytics already installed above
import sys
print(sys.version)

import torch
print(torch.__version__)

import ultralytics
print(ultralytics.__version__)

3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]
2.10.0+cu128
Creating new Ultralytics Settings v0.0.6 file ✅
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.
8.4.60

In [6]:
# dependencies included in ultralytics

In [7]:
# torchvision managed by ultralytics

In [8]:
!pip install --upgrade seaborn
!pip install --upgrade matplotlib

Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /usr/local/lib/python3.12/dist-packages (from seaborn) (2.4.6)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.12/dist-packages (from seaborn) (2.3.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /usr/local/lib/python3.12/dist-packages (from seaborn) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->seaborn) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Collecting matplotlib
  Downloading matplotlib-3.10.9-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (52 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.8/52.8 kB 2.1 MB/s eta 0:00:00
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (2.4.6)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=3 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Downloading matplotlib-3.10.9-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (8.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.8/8.8 MB 70.8 MB/s eta 0:00:00
Installing collected packages: matplotlib
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3.10.0
    Uninstalling matplotlib-3.10.0:
      Successfully uninstalled matplotlib-3.10.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigframes 2.39.0 requires google-cloud-bigquery-storage<3.0.0,>=2.30.0, which is not installed.
ydata-profiling 4.18.4 requires matplotlib<=3.10,>=3.5, but you have matplotlib 3.10.9 which is incompatible.
ydata-profiling 4.18.4 requires numba<0.63,>=0.60, but you have numba 0.65.1 which is incompatible.
ydata-profiling 4.18.4 requires numpy<2.4,>=1.22, but you have numpy 2.4.6 which is incompatible.
Successfully installed matplotlib-3.10.9

# Inference

In [9]:
import ultralytics
print(ultralytics.__version__)

8.4.60

In [10]:
from ultralytics import YOLO

model = YOLO(weights_dir)

model.predict(
    source=test_dir,
    imgsz=768,
    conf=0.01,
    iou=0.5,
    # augment=True,   # TTA
    save_txt=True,
    save_conf=True,
    # project='runs/detect',
    # name='exp',
    exist_ok=True,
    device=[0,1]
)

WARNING ⚠️
Inference results will accumulate in RAM unless `stream=True` is passed, which can cause out-of-memory errors for large
sources or long-running streams and videos. See https://docs.ultralytics.com/modes/predict/ for help.

Example:
    results = model(source=..., stream=True)  # generator of Results objects
    for r in results:
        boxes = r.boxes  # Boxes object for bbox outputs
        masks = r.masks  # Masks object for segment masks outputs
        probs = r.probs  # Class probabilities for classification outputs

image 1/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/002a34c58c5b758217ed1f584ccbcfe9.png: 768x768 4 Cardiomegalys, 6 Pleural thickenings, 1 Pulmonary fibrosis, 123.3ms
image 2/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/004f33259ee4aef671c2b95d54e4be68.png: 768x768 13 Aortic enlargements, 1 Pleural thickening, 112.9ms
image 3/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/008bdde2af2462e86fd373a445d0f4cd.png: 768x768 18 Aortic enlargements, 12 Cardiomegalys, 3 Pulmonary fibrosiss, 102.6ms
image 4/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/009bc039326338823ca3aa84381f17f1.png: 768x768 13 Aortic enlargements, 10 Cardiomegalys, 25 ILDs, 6 Infiltrations, 7 Lung Opacitys, 2 Pulmonary fibrosiss, 69.3ms
image 5/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/00a2145de1886cb9eb88869c85d74080.png: 768x768 16 Aortic enlargements, 15 Cardiomegalys, 2 Pleural thickenings, 66.1ms
image 6/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/00b7e6bfa4dc1fe9ddd0ce74743e38c2.png: 768x768 8 Aortic enlargements, 1 Calcification, 7 Cardiomegalys, 3 Consolidations, 1 ILD, 1 Infiltration, 7 Lung Opacitys, 7 Nodule/Masss, 13 Other lesions, 68.1ms
image 7/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/011295e0bcdc7636569ab73bfdcc4450.png: 768x768 1 Pleural effusion, 18 Pleural thickenings, 1 Pulmonary fibrosis, 69.9ms
image 8/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/013c169f9dad6f1f6485da961b9f7bf2.png: 768x768 1 Atelectasis, 7 Calcifications, 2 Consolidations, 4 Infiltrations, 9 Lung Opacitys, 26 Other lesions, 4 Pleural thickenings, 6 Pulmonary fibrosiss, 67.7ms
image 9/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/01431a2618c0ace741e4e270a37e20b9.png: 768x768 10 Aortic enlargements, 16 Cardiomegalys, 74.3ms
image 10/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/0168eb925aa6f28a78b16134792f5d0e.png: 768x768 1 Other lesion, 66.7ms
image 11/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/016bc723c3ceedb78e27ebfe7032498e.png: 768x768 11 Aortic enlargements, 13 Cardiomegalys, 10 Lung Opacitys, 1 Other lesion, 6 Pleural thickenings, 2 Pulmonary fibrosiss, 71.5ms
image 12/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/0171021638f9272a34a41feb84ed47a0.png: 768x768 1 Aortic enlargement, 1 Pleural effusion, 4 Pleural thickenings, 67.2ms
image 13/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/019df578e38053e614d483f7fb347b26.png: 768x768 3 Aortic enlargements, 3 ILDs, 1 Pleural thickening, 70.1ms
image 14/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/01ded16689539deb30d0981fafd18465.png: 768x768 133 Calcifications, 34 Nodule/Masss, 2 Other lesions, 5 Pleural thickenings, 60 Pulmonary fibrosiss, 69.1ms
image 15/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/01eb30a37b6f5fed8a8d3ab2d1c0a7d6.png: 768x768 12 Aortic enlargements, 75 Calcifications, 9 Cardiomegalys, 1 ILD, 5 Lung Opacitys, 43 Nodule/Masss, 9 Other lesions, 6 Pleural effusions, 5 Pleural thickenings, 11 Pulmonary fibrosiss, 62.3ms
image 16/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/01f8f17dba6c5e67ba5bcf30ce70ea3f.png: 768x768 9 Aortic enlargements, 8 Cardiomegalys, 2 ILDs, 1 Lung Opacity, 1 Other lesion, 68.8ms
image 17/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/02199417ff2a400cff64249f0399f0d7.png: 768x768 16 Aortic enlargements, 16 Cardiomegalys, 1 Pleural thickening, 69.0ms
image 18/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/022a62478444fedf2dea1ba91aafdc48.png: 768x768 2 Aortic enlargements, 7 Cardiomegalys, 67.3ms
image 19/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/02425334e92510da663eb913ad0632ea.png: 768x768 20 Aortic enlargements, 5 Cardiomegalys, 1 Pleural thickening, 70.0ms
image 20/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/024e693014e70d448f650267bed661ae.png: 768x768 7 Aortic enlargements, 13 Cardiomegalys, 1 Other lesion, 1 Pleural effusion, 4 Pleural thickenings, 67.3ms
image 21/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/0271d381c3e88527721efcfaf518be71.png: 768x768 21 Aortic enlargements, 7 Calcifications, 9 Cardiomegalys, 6 ILDs, 6 Pulmonary fibrosiss, 68.4ms
image 22/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/0291515f5d14c34180a15712a55bf7bd.png: 768x768 18 Aortic enlargements, 11 Cardiomegalys, 66.1ms
image 23/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/02b0ad6e22487b7e3f08093c42444b0f.png: 768x768 2 Aortic enlargements, 1 Consolidation, 18 Lung Opacitys, 262 Nodule/Masss, 11 Other lesions, 4 Pleural thickenings, 2 Pulmonary fibrosiss, 68.7ms
image 24/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/02d04b6b6883fd92c12a3dde5d2ff6c0.png: 768x768 13 Aortic enlargements, 30 Calcifications, 11 Cardiomegalys, 3 ILDs, 1 Lung Opacity, 1 Nodule/Mass, 66.8ms
image 25/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/034814210bf2105ecb3e7ed6876f43e9.png: 768x768 1 Nodule/Mass, 1 Other lesion, 1 Pleural thickening, 67.1ms
image 26/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/034b98d64dc012298afb3d33fe880193.png: 768x768 2 Aortic enlargements, 6 Cardiomegalys, 69.1ms
image 27/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/037503b94eb68a16587a78bce365e681.png: 768x768 20 Aortic enlargements, 14 Cardiomegalys, 1 ILD, 1 Nodule/Mass, 1 Other lesion, 69.0ms
image 28/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/037dc0be7504c7d1c5ff967f4a0a491a.png: 768x768 (no detections), 68.2ms
image 29/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/0386d9b8234215dc50eb1f66eb206d85.png: 768x768 1 Aortic enlargement, 4 Lung Opacitys, 3 Other lesions, 4 Pleural effusions, 6 Pleural thickenings, 69.8ms
image 30/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/038f69f3cf0aaa00c9d7337be434f316.png: 768x768 (no detections), 69.1ms
image 31/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/03a2e400656f58841beb7f62584ee3e9.png: 768x768 1 Pleural effusion, 10 Pleural thickenings, 69.9ms
image 32/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/03a395d9fc03a6f8c5a50e693c20ab15.png: 768x768 2 Aortic enlargements, 3 Pulmonary fibrosiss, 69.6ms
image 33/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/03aca410943c7f131b16572f03ee2cf6.png: 768x768 12 Aortic enlargements, 1 Calcification, 10 Cardiomegalys, 6 Pleural effusions, 6 Pleural thickenings, 67.8ms
image 34/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/03b796fd180662c4e579a4b8894486a9.png: 768x768 7 Aortic enlargements, 3 Cardiomegalys, 2 Pleural thickenings, 67.2ms
image 35/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/03caacd475acb947a2f11d1a0d76a971.png: 768x768 18 Aortic enlargements, 6 Cardiomegalys, 8 Other lesions, 34 Pleural effusions, 27 Pleural thickenings, 68.8ms
image 36/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/03da4593b25a2e0095170197050cb551.png: 768x768 4 Calcifications, 1 ILD, 2 Nodule/Masss, 68.3ms
image 37/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/03ea976a276b66285825246525357949.png: 768x768 6 Aortic enlargements, 7 Cardiomegalys, 3 Lung Opacitys, 4 Nodule/Masss, 1 Other lesion, 69.5ms
image 38/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/03f00327702f48c4b6726a0e1649a157.png: 768x768 15 Aortic enlargements, 14 Cardiomegalys, 6 Consolidations, 2 ILDs, 10 Infiltrations, 18 Lung Opacitys, 1 Other lesion, 10 Pleural thickenings, 69.4ms
image 39/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/03f4ef7ff19190f220b13c0059ac506b.png: 768x768 4 Pleural thickenings, 66.4ms
image 40/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/03f9ce3f34a38cf5c6411acd8fd4c5ff.png: 768x768 3 Pleural thickenings, 69.8ms
image 41/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/0403dda5a9bf46457517b604869d530d.png: 768x768 2 Pleural thickenings, 1 Pulmonary fibrosis, 69.6ms
image 42/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/041c40e3f03d9af32b594c5186575a61.png: 768x768 28 Calcifications, 4 ILDs, 1 Other lesion, 67.8ms
image 43/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/043111cdad4d26204503d3396876046f.png: 768x768 5 Pleural effusions, 3 Pleural thickenings, 68.1ms
image 44/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/045a16fa7dd72c16b7b7d44ff10be428.png: 768x768 7 Aortic enlargements, 1 Calcification, 11 Cardiomegalys, 4 Other lesions, 69.8ms
image 45/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/0461006c3061e71f2cf28da9565d7288.png: 768x768 12 Atelectasiss, 4 Cardiomegalys, 2 Consolidations, 5 ILDs, 1 Infiltration, 7 Lung Opacitys, 5 Other lesions, 5 Pleural effusions, 4 Pneumothoraxs, 9 Pulmonary fibrosiss, 68.6ms
image 46/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/04669ec4821d2dde14eb2f9a3f47eb7e.png: 768x768 18 Aortic enlargements, 1 Calcification, 11 Cardiomegalys, 10 Pleural thickenings, 16 Pulmonary fibrosiss, 67.3ms
image 47/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/047815a469503dfe21da4a12e2514a15.png: 768x768 3 Cardiomegalys, 1 Pleural effusion, 68.1ms
image 48/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/048ce999447fbb6a58ea17fac775288b.png: 768x768 5 Atelectasiss, 6 Calcifications, 3 Cardiomegalys, 67.1ms
image 49/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/0493431e2beef20230dfc2837e95fe7b.png: 768x768 3 Pleural thickenings, 67.2ms
image 50/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/0493df0059bd251e6dbb0dc71f5c5b45.png: 768x768 8 Aortic enlargements, 4 Calcifications, 22 Cardiomegalys, 5 ILDs, 20 Other lesions, 70.2ms
image 51/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/04b68e83e611caf345b0a1dc9c65ec88.png: 768x768 16 Aortic enlargements, 7 Cardiomegalys, 3 Pleural thickenings, 3 Pulmonary fibrosiss, 68.1ms
image 52/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/04b700c4815f088728db9f093c739707.png: 768x768 3 Aortic enlargements, 6 Pleural thickenings, 67.8ms
image 53/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/04c6efbd31a676bb888a4f5bf53d03c1.png: 768x768 4 Aortic enlargements, 10 Infiltrations, 5 Lung Opacitys, 1 Other lesion, 1 Pleural effusion, 1 Pleural thickening, 4 Pulmonary fibrosiss, 68.1ms
image 54/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/04cc236166c1ff638ff6200f2f2a397d.png: 768x768 13 Aortic enlargements, 5 Cardiomegalys, 6 Pulmonary fibrosiss, 67.2ms
image 55/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/04da0054eed9aa1c8b95ade5e6c16a00.png: 768x768 1 Lung Opacity, 54 Other lesions, 1 Pleural effusion, 2 Pleural thickenings, 68.3ms
image 56/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/051b1b1edcbaa44059c7b3edbe70c3b8.png: 768x768 5 Aortic enlargements, 7 Cardiomegalys, 8 Lung Opacitys, 20 Pleural effusions, 8 Pleural thickenings, 67.2ms
image 57/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/0538230ced64be2db111ff5d07624db1.png: 768x768 1 Pulmonary fibrosis, 68.6ms
image 58/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/056815f22ac3de9b9eb6fb963d4cfa5a.png: 768x768 1 ILD, 70.5ms
image 59/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/05711a72a0819422965daa93f30b6f75.png: 768x768 9 Aortic enlargements, 8 Lung Opacitys, 10 Nodule/Masss, 2 Other lesions, 5 Pleural thickenings, 1 Pulmonary fibrosis, 67.5ms
image 60/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/057afd48abd153972bb91397b71b66b8.png: 768x768 2 Aortic enlargements, 7 Calcifications, 6 Consolidations, 2 ILDs, 10 Infiltrations, 18 Lung Opacitys, 36 Nodule/Masss, 8 Other lesions, 3 Pleural thickenings, 14 Pulmonary fibrosiss, 69.1ms
image 61/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/05857909cbf214a6cbdef5306e18d48e.png: 768x768 18 Aortic enlargements, 12 Cardiomegalys, 1 ILD, 5 Pleural thickenings, 68.5ms
image 62/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/059ad332961631d8d2f4ab468a7e42d3.png: 768x768 11 ILDs, 1 Pleural thickening, 72.8ms
image 63/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/05a548fd37b6e44ab97a48dabee57c21.png: 768x768 2 Aortic enlargements, 1 Cardiomegaly, 2 ILDs, 1 Infiltration, 1 Lung Opacity, 2 Other lesions, 2 Pleural thickenings, 1 Pulmonary fibrosis, 73.4ms
image 64/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/05a7460866e0d128b5db471431675483.png: 768x768 15 ILDs, 1 Nodule/Mass, 1 Other lesion, 68.5ms
image 65/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/05dbd765ff84cbb24759b0c135ba4447.png: 768x768 16 Aortic enlargements, 1 Pleural thickening, 2 Pulmonary fibrosiss, 67.0ms
image 66/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/05e951c63e80999f13e6e09e7ec8439a.png: 768x768 6 Aortic enlargements, 1 Cardiomegaly, 2 Pleural effusions, 32 Pleural thickenings, 26 Pulmonary fibrosiss, 69.0ms
image 67/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/05fd4bbf127858eb83ae01cd454d3e2a.png: 768x768 10 Aortic enlargements, 10 Cardiomegalys, 1 ILD, 66.8ms
image 68/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/065473884bfa339d2e464e5394d56fd6.png: 768x768 6 Aortic enlargements, 9 Cardiomegalys, 3 Pleural thickenings, 69.1ms
image 69/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/069198879ff8140bab6c47c58242a0a4.png: 768x768 1 Other lesion, 1 Pulmonary fibrosis, 68.7ms
image 70/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/0713502741102f3e494fb39bbd9f9571.png: 768x768 2 Aortic enlargements, 1 Pleural thickening, 68.3ms
image 71/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/071e3d1deecabb75178035e8dbad8b4d.png: 768x768 12 Aortic enlargements, 1 Nodule/Mass, 69.4ms
image 72/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/07229c769cb2c284c1114c6fe7ed3dd6.png: 768x768 4 Aortic enlargements, 6 ILDs, 1 Nodule/Mass, 69.4ms
image 73/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/07304e029b89fc007bd64b7c9bb52979.png: 768x768 1 Aortic enlargement, 1 ILD, 2 Nodule/Masss, 1 Other lesion, 1 Pulmonary fibrosis, 68.3ms
image 74/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/074e3cceb0c1677a1ad0dbff31167d7d.png: 768x768 2 Aortic enlargements, 1 Cardiomegaly, 14 Consolidations, 4 Infiltrations, 23 Lung Opacitys, 9 Nodule/Masss, 51 Pleural effusions, 12 Pleural thickenings, 2 Pulmonary fibrosiss, 70.1ms
image 75/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/0764ce517782604a7b81bb6e17c798e9.png: 768x768 1 Aortic enlargement, 6 Calcifications, 5 Cardiomegalys, 1 ILD, 3 Other lesions, 6 Pleural thickenings, 2 Pulmonary fibrosiss, 66.1ms
image 76/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/0792bb20718b8006f78094ae449c3c96.png: 768x768 4 Aortic enlargements, 1 Atelectasis, 4 Calcifications, 8 Cardiomegalys, 2 ILDs, 70.0ms
image 77/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/0799063103aea263344a77adbde5b7ca.png: 768x768 3 Aortic enlargements, 6 Cardiomegalys, 17 Pleural effusions, 10 Pleural thickenings, 69.4ms
image 78/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/079de341c7b3804c37114b8da3011b45.png: 768x768 6 Aortic enlargements, 3 Cardiomegalys, 1 Infiltration, 1 Lung Opacity, 1 Other lesion, 67.3ms
image 79/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/07c1810b7cb0d7ef900ab2b0007784cf.png: 768x768 14 Aortic enlargements, 1 Lung Opacity, 1 Other lesion, 4 Pleural effusions, 5 Pleural thickenings, 66.9ms
image 80/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/07cdcea9a6c3049d7a02ade9c680d4d7.png: 768x768 2 ILDs, 24 Infiltrations, 38 Lung Opacitys, 5 Nodule/Masss, 5 Other lesions, 2 Pleural effusions, 10 Pleural thickenings, 26 Pulmonary fibrosiss, 69.1ms
image 81/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/07dcda506753ae678e2cc937f1f8ddf2.png: 768x768 4 Aortic enlargements, 30 Pleural thickenings, 69.1ms
image 82/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/07ea0f8d7b7f1fb150c5afb04dc26c9a.png: 768x768 14 Aortic enlargements, 2 Infiltrations, 3 Lung Opacitys, 1 Other lesion, 1 Pleural thickening, 68.1ms
image 83/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/07ee04ca7bb66d99ae283ded05f1af76.png: 768x768 3 Cardiomegalys, 2 ILDs, 66.4ms
image 84/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/07ee5d541dcbf1131f0b84aee73d7705.png: 768x768 4 Cardiomegalys, 1 ILD, 71.6ms
image 85/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/07fecb6f57a3d452c4764b1013740141.png: 768x768 17 Aortic enlargements, 12 Cardiomegalys, 3 ILDs, 2 Lung Opacitys, 8 Pulmonary fibrosiss, 72.0ms
image 86/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/080fd678b461536e6e1b5d9b17093cdb.png: 768x768 13 Aortic enlargements, 10 Calcifications, 7 Cardiomegalys, 5 ILDs, 2 Nodule/Masss, 4 Other lesions, 4 Pleural thickenings, 68.0ms
image 87/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/08504fa0ea409654d6328e51de2fb3b9.png: 768x768 8 Aortic enlargements, 11 Pleural effusions, 19 Pleural thickenings, 1 Pulmonary fibrosis, 69.2ms
image 88/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/08534e46be27043b31a2b648d7c62350.png: 768x768 6 Aortic enlargements, 1 Pleural effusion, 6 Pleural thickenings, 72.9ms
image 89/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/08807797eff7d24d76e4817a3a38477e.png: 768x768 22 Aortic enlargements, 3 Atelectasiss, 38 Calcifications, 9 Cardiomegalys, 18 ILDs, 2 Infiltrations, 7 Lung Opacitys, 13 Nodule/Masss, 3 Other lesions, 6 Pulmonary fibrosiss, 69.8ms
image 90/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/08cad5510452011e9c519bbbc9741fda.png: 768x768 1 Aortic enlargement, 66.7ms
image 91/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/08d6125cda5ffceb8f235c96179a7061.png: 768x768 9 Cardiomegalys, 1 ILD, 70.5ms
image 92/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/08e4edc0d35455c8e25a74b9ed3137b0.png: 768x768 2 Calcifications, 4 Cardiomegalys, 3 Other lesions, 67.9ms
image 93/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/08ee53ea1825d6e2feffc2a6488f2d7d.png: 768x768 9 Aortic enlargements, 7 Calcifications, 12 Lung Opacitys, 8 Nodule/Masss, 8 Other lesions, 1 Pleural thickening, 6 Pulmonary fibrosiss, 69.3ms
image 94/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/090a90ca6e01ed9f613578c95c151a01.png: 768x768 (no detections), 67.8ms
image 95/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/0919cca5a55ea3b156f45b5cd14fe8d3.png: 768x768 1 Pleural effusion, 2 Pleural thickenings, 70.8ms
image 96/3000 /kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/09291f525b50263a1b90764715395311.png: 768x768 14 Aortic enlargements, 4 Cardiomegalys, 67.5ms

[ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'Aortic enlargement', 1: 'Atelectasis', 2: 'Calcification', 3: 'Cardiomegaly', 4: 'Consolidation', 5: 'ILD', 6: 'Infiltration', 7: 'Lung Opacity', 8: 'Nodule/Mass', 9: 'Other lesion', 10: 'Pleural effusion', 11: 'Pleural thickening', 12: 'Pneumothorax', 13: 'Pulmonary fibrosis'}
 obb: None
 orig_img: array([[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         ...,
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         ...,
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         ...,
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        ...,

        [[13, 13, 13],
         [14, 14, 14],
         [15, 15, 15],
         ...,
         [45, 45, 45],
         [44, 44, 44],
         [43, 43, 43]],

        [[14, 14, 14],
         [14, 14, 14],
         [16, 16, 16],
         ...,
         [44, 44, 44],
         [44, 44, 44],
         [42, 42, 42]],

        [[14, 14, 14],
         [16, 16, 16],
         [15, 15, 15],
         ...,
         [44, 44, 44],
         [44, 44, 44],
         [41, 41, 41]]], shape=(1024, 1024, 3), dtype=uint8)
 orig_shape: (1024, 1024)
 path: '/kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/002a34c58c5b758217ed1f584ccbcfe9.png'
 probs: None
 save_dir: '/kaggle/working/runs/detect/predict'
 semantic_mask: None
 speed: {'preprocess': 9.215617999871029, 'inference': 123.32723999998052, 'postprocess': 31.932818999848678},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'Aortic enlargement', 1: 'Atelectasis', 2: 'Calcification', 3: 'Cardiomegaly', 4: 'Consolidation', 5: 'ILD', 6: 'Infiltration', 7: 'Lung Opacity', 8: 'Nodule/Mass', 9: 'Other lesion', 10: 'Pleural effusion', 11: 'Pleural thickening', 12: 'Pneumothorax', 13: 'Pulmonary fibrosis'}
 obb: None
 orig_img: array([[[ 13,  13,  13],
         [ 13,  13,  13],
         [ 13,  13,  13],
         ...,
         [  6,   6,   6],
         [  6,   6,   6],
         [  5,   5,   5]],

        [[ 13,  13,  13],
         [ 13,  13,  13],
         [ 13,  13,  13],
         ...,
         [  6,   6,   6],
         [  6,   6,   6],
         [  6,   6,   6]],

        [[ 12,  12,  12],
         [ 13,  13,  13],
         [ 12,  12,  12],
         ...,
         [  6,   6,   6],
         [  6,   6,   6],
         [  6,   6,   6]],

        ...,

        [[216, 216, 216],
         [215, 215, 215],
         [217, 217, 217],
         ...,
         [198, 198, 198],
         [194, 194, 194],
         [196, 196, 196]],

        [[216, 216, 216],
         [217, 217, 217],
         [216, 216, 216],
         ...,
         [200, 200, 200],
         [198, 198, 198],
         [198, 198, 198]],

        [[215, 215, 215],
         [217, 217, 217],
         [215, 215, 215],
         ...,
         [197, 197, 197],
         [196, 196, 196],
         [196, 196, 196]]], shape=(1024, 1024, 3), dtype=uint8)
 orig_shape: (1024, 1024)
 path: '/kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/004f33259ee4aef671c2b95d54e4be68.png'
 probs: None
 save_dir: '/kaggle/working/runs/detect/predict'
 semantic_mask: None
 speed: {'preprocess': 3.7356960001488915, 'inference': 112.86446299982344, 'postprocess': 0.42181999992862984},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'Aortic enlargement', 1: 'Atelectasis', 2: 'Calcification', 3: 'Cardiomegaly', 4: 'Consolidation', 5: 'ILD', 6: 'Infiltration', 7: 'Lung Opacity', 8: 'Nodule/Mass', 9: 'Other lesion', 10: 'Pleural effusion', 11: 'Pleural thickening', 12: 'Pneumothorax', 13: 'Pulmonary fibrosis'}
 obb: None
 orig_img: array([[[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0]],

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0]],

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0]],

        ...,

        [[  2,   2,   2],
         [  2,   2,   2],
         [  2,   2,   2],
         ...,
         [171, 171, 171],
         [167, 167, 167],
         [167, 167, 167]],

        [[  2,   2,   2],
         [  2,   2,   2],
         [  2,   2,   2],
         ...,
         [174, 174, 174],
         [166, 166, 166],
         [163, 163, 163]],

        [[  2,   2,   2],
         [  2,   2,   2],
         [  1,   1,   1],
         ...,
         [178, 178, 178],
         [175, 175, 175],
         [170, 170, 170]]], shape=(1024, 1024, 3), dtype=uint8)
 orig_shape: (1024, 1024)
 path: '/kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/008bdde2af2462e86fd373a445d0f4cd.png'
 probs: None
 save_dir: '/kaggle/working/runs/detect/predict'
 semantic_mask: None
 speed: {'preprocess': 3.603619999921648, 'inference': 102.63961200007543, 'postprocess': 0.4035200001908379},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'Aortic enlargement', 1: 'Atelectasis', 2: 'Calcification', 3: 'Cardiomegaly', 4: 'Consolidation', 5: 'ILD', 6: 'Infiltration', 7: 'Lung Opacity', 8: 'Nodule/Mass', 9: 'Other lesion', 10: 'Pleural effusion', 11: 'Pleural thickening', 12: 'Pneumothorax', 13: 'Pulmonary fibrosis'}
 obb: None
 orig_img: array([[[40, 40, 40],
         [41, 41, 41],
         [43, 43, 43],
         ...,
         [ 3,  3,  3],
         [ 3,  3,  3],
         [ 1,  1,  1]],

        [[42, 42, 42],
         [44, 44, 44],
         [46, 46, 46],
         ...,
         [ 3,  3,  3],
         [ 3,  3,  3],
         [ 1,  1,  1]],

        [[46, 46, 46],
         [48, 48, 48],
         [49, 49, 49],
         ...,
         [ 3,  3,  3],
         [ 3,  3,  3],
         [ 1,  1,  1]],

        ...,

        [[ 7,  7,  7],
         [ 7,  7,  7],
         [ 7,  7,  7],
         ...,
         [ 1,  1,  1],
         [ 1,  1,  1],
         [ 0,  0,  0]],

        [[ 6,  6,  6],
         [ 7,  7,  7],
         [ 7,  7,  7],
         ...,
         [ 1,  1,  1],
         [ 1,  1,  1],
         [ 0,  0,  0]],

        [[ 5,  5,  5],
         [ 5,  5,  5],
         [ 5,  5,  5],
         ...,
         [ 1,  1,  1],
         [ 1,  1,  1],
         [ 0,  0,  0]]], shape=(1024, 1024, 3), dtype=uint8)
 orig_shape: (1024, 1024)
 path: '/kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/009bc039326338823ca3aa84381f17f1.png'
 probs: None
 save_dir: '/kaggle/working/runs/detect/predict'
 semantic_mask: None
 speed: {'preprocess': 3.4428429999024956, 'inference': 69.33841799991569, 'postprocess': 0.4228110001349705},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'Aortic enlargement', 1: 'Atelectasis', 2: 'Calcification', 3: 'Cardiomegaly', 4: 'Consolidation', 5: 'ILD', 6: 'Infiltration', 7: 'Lung Opacity', 8: 'Nodule/Mass', 9: 'Other lesion', 10: 'Pleural effusion', 11: 'Pleural thickening', 12: 'Pneumothorax', 13: 'Pulmonary fibrosis'}
 obb: None
 orig_img: array([[[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0]],

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [ 72,  72,  72],
         [  4,   4,   4],
         [  0,   0,   0]],

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [  0,   0,   0],
         [160, 160, 160],
         [  0,   0,   0]],

        ...,

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0]],

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0]],

        [[117, 117, 117],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0]]], shape=(1024, 1024, 3), dtype=uint8)
 orig_shape: (1024, 1024)
 path: '/kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/00a2145de1886cb9eb88869c85d74080.png'
 probs: None
 save_dir: '/kaggle/working/runs/detect/predict'
 semantic_mask: None
 speed: {'preprocess': 3.340208999816241, 'inference': 66.0742330001085, 'postprocess': 0.3821630000402365},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'Aortic enlargement', 1: 'Atelectasis', 2: 'Calcification', 3: 'Cardiomegaly', 4: 'Consolidation', 5: 'ILD', 6: 'Infiltration', 7: 'Lung Opacity', 8: 'Nodule/Mass', 9: 'Other lesion', 10: 'Pleural effusion', 11: 'Pleural thickening', 12: 'Pneumothorax', 13: 'Pulmonary fibrosis'}
 obb: None
 orig_img: array([[[60, 60, 60],
         [48, 48, 48],
         [57, 57, 57],
         ...,
         [29, 29, 29],
         [33, 33, 33],
         [30, 30, 30]],

        [[60, 60, 60],
         [47, 47, 47],
         [55, 55, 55],
         ...,
         [29, 29, 29],
         [31, 31, 31],
         [25, 25, 25]],

        [[60, 60, 60],
         [44, 44, 44],
         [60, 60, 60],
         ...,
         [30, 30, 30],
         [34, 34, 34],
         [28, 28, 28]],

        ...,

        [[55, 55, 55],
         [56, 56, 56],
         [55, 55, 55],
         ...,
         [18, 18, 18],
         [22, 22, 22],
         [18, 18, 18]],

        [[52, 52, 52],
         [56, 56, 56],
         [57, 57, 57],
         ...,
         [18, 18, 18],
         [21, 21, 21],
         [19, 19, 19]],

        [[53, 53, 53],
         [54, 54, 54],
         [53, 53, 53],
         ...,
         [19, 19, 19],
         [20, 20, 20],
         [16, 16, 16]]], shape=(1024, 1024, 3), dtype=uint8)
 orig_shape: (1024, 1024)
 path: '/kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/00b7e6bfa4dc1fe9ddd0ce74743e38c2.png'
 probs: None
 save_dir: '/kaggle/working/runs/detect/predict'
 semantic_mask: None
 speed: {'preprocess': 3.2857960000001185, 'inference': 68.14645800000108, 'postprocess': 0.3706139998485014},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'Aortic enlargement', 1: 'Atelectasis', 2: 'Calcification', 3: 'Cardiomegaly', 4: 'Consolidation', 5: 'ILD', 6: 'Infiltration', 7: 'Lung Opacity', 8: 'Nodule/Mass', 9: 'Other lesion', 10: 'Pleural effusion', 11: 'Pleural thickening', 12: 'Pneumothorax', 13: 'Pulmonary fibrosis'}
 obb: None
 orig_img: array([[[7, 7, 7],
         [6, 6, 6],
         [6, 6, 6],
         ...,
         [3, 3, 3],
         [3, 3, 3],
         [1, 1, 1]],

        [[6, 6, 6],
         [7, 7, 7],
         [7, 7, 7],
         ...,
         [3, 3, 3],
         [3, 3, 3],
         [1, 1, 1]],

        [[6, 6, 6],
         [6, 6, 6],
         [6, 6, 6],
         ...,
         [3, 3, 3],
         [3, 3, 3],
         [1, 1, 1]],

        ...,

        [[6, 6, 6],
         [6, 6, 6],
         [6, 6, 6],
         ...,
         [4, 4, 4],
         [4, 4, 4],
         [2, 2, 2]],

        [[6, 6, 6],
         [6, 6, 6],
         [6, 6, 6],
         ...,
         [4, 4, 4],
         [4, 4, 4],
         [2, 2, 2]],

        [[4, 4, 4],
         [4, 4, 4],
         [4, 4, 4],
         ...,
         [3, 3, 3],
         [3, 3, 3],
         [1, 1, 1]]], shape=(1024, 1024, 3), dtype=uint8)
 orig_shape: (1024, 1024)
 path: '/kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/011295e0bcdc7636569ab73bfdcc4450.png'
 probs: None
 save_dir: '/kaggle/working/runs/detect/predict'
 semantic_mask: None
 speed: {'preprocess': 3.459757999962676, 'inference': 69.93292499987547, 'postprocess': 0.37932700001874764},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'Aortic enlargement', 1: 'Atelectasis', 2: 'Calcification', 3: 'Cardiomegaly', 4: 'Consolidation', 5: 'ILD', 6: 'Infiltration', 7: 'Lung Opacity', 8: 'Nodule/Mass', 9: 'Other lesion', 10: 'Pleural effusion', 11: 'Pleural thickening', 12: 'Pneumothorax', 13: 'Pulmonary fibrosis'}
 obb: None
 orig_img: array([[[183, 183, 183],
         [166, 166, 166],
         [165, 165, 165],
         ...,
         [  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0]],

        [[167, 167, 167],
         [153, 153, 153],
         [150, 150, 150],
         ...,
         [  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0]],

        [[154, 154, 154],
         [144, 144, 144],
         [134, 134, 134],
         ...,
         [  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0]],

        ...,

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0]],

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0]],

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0]]], shape=(1024, 1024, 3), dtype=uint8)
 orig_shape: (1024, 1024)
 path: '/kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/013c169f9dad6f1f6485da961b9f7bf2.png'
 probs: None
 save_dir: '/kaggle/working/runs/detect/predict'
 semantic_mask: None
 speed: {'preprocess': 3.4568559999570425, 'inference': 67.65901200014923, 'postprocess': 0.4013610000583867},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'Aortic enlargement', 1: 'Atelectasis', 2: 'Calcification', 3: 'Cardiomegaly', 4: 'Consolidation', 5: 'ILD', 6: 'Infiltration', 7: 'Lung Opacity', 8: 'Nodule/Mass', 9: 'Other lesion', 10: 'Pleural effusion', 11: 'Pleural thickening', 12: 'Pneumothorax', 13: 'Pulmonary fibrosis'}
 obb: None
 orig_img: array([[[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0]],

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0]],

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0]],

        ...,

        [[  1,   1,   1],
         [  1,   1,   1],
         [  1,   1,   1],
         ...,
         [159, 159, 159],
         [159, 159, 159],
         [149, 149, 149]],

        [[  1,   1,   1],
         [  1,   1,   1],
         [  1,   1,   1],
         ...,
         [154, 154, 154],
         [155, 155, 155],
         [155, 155, 155]],

        [[  1,   1,   1],
         [  1,   1,   1],
         [  1,   1,   1],
         ...,
         [160, 160, 160],
         [158, 158, 158],
         [150, 150, 150]]], shape=(1024, 1024, 3), dtype=uint8)
 orig_shape: (1024, 1024)
 path: '/kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/01431a2618c0ace741e4e270a37e20b9.png'
 probs: None
 save_dir: '/kaggle/working/runs/detect/predict'
 semantic_mask: None
 speed: {'preprocess': 3.30398599999171, 'inference': 74.32794900000772, 'postprocess': 0.37065299989080813},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'Aortic enlargement', 1: 'Atelectasis', 2: 'Calcification', 3: 'Cardiomegaly', 4: 'Consolidation', 5: 'ILD', 6: 'Infiltration', 7: 'Lung Opacity', 8: 'Nodule/Mass', 9: 'Other lesion', 10: 'Pleural effusion', 11: 'Pleural thickening', 12: 'Pneumothorax', 13: 'Pulmonary fibrosis'}
 obb: None
 orig_img: array([[[5, 5, 5],
         [5, 5, 5],
         [5, 5, 5],
         ...,
         [9, 9, 9],
         [9, 9, 9],
         [8, 8, 8]],

        [[5, 5, 5],
         [5, 5, 5],
         [6, 6, 6],
         ...,
         [8, 8, 8],
         [8, 8, 8],
         [8, 8, 8]],

        [[5, 5, 5],
         [6, 6, 6],
         [5, 5, 5],
         ...,
         [9, 9, 9],
         [8, 8, 8],
         [8, 8, 8]],

        ...,

        [[6, 6, 6],
         [6, 6, 6],
         [5, 5, 5],
         ...,
         [7, 7, 7],
         [7, 7, 7],
         [7, 7, 7]],

        [[6, 6, 6],
         [6, 6, 6],
         [6, 6, 6],
         ...,
         [7, 7, 7],
         [7, 7, 7],
         [7, 7, 7]],

        [[6, 6, 6],
         [6, 6, 6],
         [6, 6, 6],
         ...,
         [7, 7, 7],
         [7, 7, 7],
         [7, 7, 7]]], shape=(1024, 1024, 3), dtype=uint8)
 orig_shape: (1024, 1024)
 path: '/kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/0168eb925aa6f28a78b16134792f5d0e.png'
 probs: None
 save_dir: '/kaggle/working/runs/detect/predict'
 semantic_mask: None
 speed: {'preprocess': 3.9206680000916094, 'inference': 66.72036300005857, 'postprocess': 0.4824220000045898},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'Aortic enlargement', 1: 'Atelectasis', 2: 'Calcification', 3: 'Cardiomegaly', 4: 'Consolidation', 5: 'ILD', 6: 'Infiltration', 7: 'Lung Opacity', 8: 'Nodule/Mass', 9: 'Other lesion', 10: 'Pleural effusion', 11: 'Pleural thickening', 12: 'Pneumothorax', 13: 'Pulmonary fibrosis'}
 obb: None
 orig_img: array([[[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [  3,   3,   3],
         [  3,   3,   3],
         [  1,   1,   1]],

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [  3,   3,   3],
         [  3,   3,   3],
         [  1,   1,   1]],

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [  3,   3,   3],
         [  3,   3,   3],
         [  1,   1,   1]],

        ...,

        [[151, 151, 151],
         [153, 153, 153],
         [155, 155, 155],
         ...,
         [ 61,  61,  61],
         [ 63,  63,  63],
         [ 32,  32,  32]],

        [[154, 154, 154],
         [154, 154, 154],
         [156, 156, 156],
         ...,
         [ 61,  61,  61],
         [ 64,  64,  64],
         [ 32,  32,  32]],

        [[107, 107, 107],
         [108, 108, 108],
         [108, 108, 108],
         ...,
         [ 43,  43,  43],
         [ 44,  44,  44],
         [ 22,  22,  22]]], shape=(1024, 1024, 3), dtype=uint8)
 orig_shape: (1024, 1024)
 path: '/kaggle/input/vinbigdata-1024-image-dataset/vinbigdata/test/016bc723c3ceedb78e27ebfe7032498e.png'
 probs: None
 save_dir: '/kaggle/working/runs/detect/predict'
 semantic_mask: None
 speed: {'preprocess': 3.412133999972866, 'inference': 71.46317899992027, 'postprocess': 0.35359399998924346},
 ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None

# Process Submission

In [11]:
!pip install pandas==1.1.5

Collecting pandas==1.1.5
  Downloading pandas-1.1.5.tar.gz (5.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 49.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

In [12]:
def yolo2voc(image_height, image_width, bboxes):
    """
    yolo => [xmid, ymid, w, h] (normalized)
    voc  => [x1, y1, x2, y1]
    
    """ 
    bboxes = bboxes.copy().astype(float) # otherwise all value will be 0 as voc_pascal dtype is np.int
    
    bboxes[..., [0, 2]] = bboxes[..., [0, 2]]* image_width
    bboxes[..., [1, 3]] = bboxes[..., [1, 3]]* image_height
    
    bboxes[..., [0, 1]] = bboxes[..., [0, 1]] - bboxes[..., [2, 3]]/2
    bboxes[..., [2, 3]] = bboxes[..., [0, 1]] + bboxes[..., [2, 3]]
    
    return bboxes

In [13]:
image_ids = []
PredictionStrings = []

for file_path in tqdm(glob('runs/detect/predict/labels/*txt')):
    image_id = file_path.split('/')[-1].split('.')[0]
    w, h = test_df.loc[test_df.image_id==image_id,['width', 'height']].values[0]
    f = open(file_path, 'r')
    data = np.array(f.read().replace('\n', ' ').strip().split(' ')).astype(np.float32).reshape(-1, 6)
    data = data[:, [0, 5, 1, 2, 3, 4]]
#     bboxes = list(np.round(np.concatenate((data[:, :2], np.round(yolo2voc(h, w, data[:, 2:]))), axis =1).reshape(-1), 1).astype(str))
    bboxes = list(np.round(np.concatenate((data[:, :2], np.round(yolo2voc(h, w, data[:, 2:]))), axis =1).reshape(-1), 3).astype(str))
    for idx in range(len(bboxes)):
        bboxes[idx] = str(int(float(bboxes[idx]))) if idx%6!=1 else bboxes[idx]
    image_ids.append(image_id)
    PredictionStrings.append(' '.join(bboxes))

  0%|          | 0/2908 [00:00<?, ?it/s]

In [14]:
pred_df = pd.DataFrame({'image_id':image_ids,
                        'PredictionString':PredictionStrings})
sub_df = pd.merge(test_df, pred_df, on = 'image_id', how = 'left').fillna("14 1 0 0 1 1")
sub_df = sub_df[['image_id', 'PredictionString']]
sub_df.to_csv('/kaggle/working/yolo26x_fold4_finetune768_submission.csv',index = False)
sub_df.tail()

,image_id,PredictionString
2995,7f5503caa936a623b4388fbd88e890c5,14 1 0 0 1 1
2996,c97e54a78bab9c05ce2e04fe6c284bcd,0 0.645 1703 976 2065 1409 0 0.509 1707 977 20...
2997,33218cf183c1224a74ccfb514e827e15,3 0.442 944 1357 1886 1798 7 0.325 495 737 108...
2998,04b700c4815f088728db9f093c739707,0 0.199 1311 1069 1576 1340 0 0.12 1285 1059 1...
2999,14da9051525bd2504dd56938f92644ef,0 0.338 984 809 1200 1034 0 0.037 1022 810 119...

In [15]:
len(sub_df)

3000

In [16]:
# no cleanup needed (ultralytics does not create a working dir)